PORTNAME=	yaml
PORTVERSION=	0.4.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	YAML Ain't Markup Language
WWW=		https://github.com/ruby/yaml

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual
LICENSE_FILE_BSD2CLAUSE=	${WRKSRC}/BSDL
LICENSE_FILE_RUBY=		${WRKSRC}/COPYING

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
