PORTNAME=	repl_type_completor
PORTVERSION=	0.1.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	hs@on-sky.net
COMMENT=	Type based completion for REPL.
WWW=		https://github.com/ruby/repl_type_completor

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
